### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zenglongjin** [3UTR/DaPars2#10]
Dear Feng:
We do not admit to intact http://tc3a.org based on DaPars2. Thank you very much for your attention and consideration.

**Comment by 3UTR** [comment]
Hi zenglongjin,

TC3A is now temporarily closed as the lab is now moving to University of California, Irvine.

You can still access the data with doi: 0.7303/syn24982198 or directly access https://www.synapse.org/#!Synapse:syn24982198/files/. Sorry for the inconvenience.
