### ISSUE TITLE
Why is DaPars2_Multi_Sample_Multi_Chr.py hardcoded for human genome?

### ISSUE THREAD

**Issue by dzhaobio** [3UTR/DaPars2#14]
Does the method only apply to human data?

I tried it on mouse data. I constantly ran into errors. Finally I found the variable "All_chroms" was hard-coded to human genome.

[lines 112-118](https://github.com/3UTR/DaPars2/blob/23d89d1bd79faebc86abeff090ff7e981ef3bbb7/src/DaPars2_Multi_Sample_Multi_Chr.py#L112) in DaPars2_Multi_Sample_Multi_Chr.py 

```
    All_chroms = []
    All_chroms.append('chrX')
    All_chroms.append('chrY')

    for i in range(22):
        curr_chr = 'chr%i' % (i+1)
        All_chroms.append(curr_chr)
```

If this method is not limited to human genome, the code should be fixed to make it work for general genomes. The authors should not assume how the chromosomes are named. For example, there is not always "chr" in chromosome names. The chromosome names should be obtained from the data provided. If it does not work for general genomes, it will definitely make users frustrated.

**Comment by 3UTR** [comment]
Hi dzhaobio,

Curent code only apply to human data, but we will update to make it more general.

Thanks.
