### ISSUE TITLE
tc3a.org Website：18.223.209.34‘s server 403 Forbidden

### ISSUE THREAD

**Issue by PinkSmallFan** [3UTR/DaPars2#3]
Hello, Happy new year... 

When I tried to use the TC3A site, unfortunately, the server was down.

![image](https://user-images.githubusercontent.com/43728530/108452954-7189ee80-72a4-11eb-8fb6-25f432856596.png)

**Comment by 3UTR** [comment]
TC3A is now temporarily closed, but you can still access the data with doi: 0.7303/syn24982198 or directly access https://www.synapse.org/#!Synapse:syn24982198/files/.
