### ISSUE TITLE
hg19_4_19_2012_Refseq_id_from_UCSC.txt #9

### ISSUE THREAD

**Issue by huangrongbioinfomation** [3UTR/DaPars2#4]
excuse me , where the hg19_4_19_2012_Refseq_id_from_UCSC.txt come from?

**Comment by YiPeng-Gao** [comment]
> excuse me , where the hg19_4_19_2012_Refseq_id_from_UCSC.txt come from?

Please refer to the DaPars test dataset file "Refseq_id_from_UCSC.txt". You can generate this file from UCSC.
